config/routes.rb
Enki::Application.routes.draw do
  get 'search'  => 'search#show'

  namespace :admin do
    resource :session

    resources :posts, :pages do
      post 'preview', :on => :collection
    end
    resources :comments
    resources :undo_items do
      post 'undo', :on => :member
    end
    # add upload file
    resources :pubfiles do
      get 'download', :on => :member    
    end
    resources :pubimages do
      get 'download', :on => :member  
    end

    get 'health(/:action)' => 'health', :action => 'index', :as => :health
    post 'health/generate_exception' => 'health#generate_exception'

    root :to => 'dashboard#show'
  end

  resources :archives, :only => [:index]
  resources :pages, :only => [:show]

  constraints :year => /\d{4}/, :month => /\d{2}/, :day => /\d{2}/ do
    get ':year/:month/:day/:slug/comments'  => 'comments#index'
    post ':year/:month/:day/:slug/comments' => 'comments#create'
    get ':year/:month/:day/:slug/comments/new' => 'comments#new'
    get ':year/:month/:day/:slug' => 'posts#show'
  end

  scope :to => 'posts#index' do
    get 'posts.:format', :as => :formatted_posts
    get '(:tag)', :as => :posts, :tag => /(?:[A-Za-z0-9_ \.-]|%20)+?/, :format => /html|atom/
  end

  # OmniAuth routes.
  post 'auth/open_id_comment/callback', :to => 'comments#create'
  match 'auth/failure' => 'comments#create',
  :constraints => lambda { |request|
    request.query_parameters[:strategy] == ApplicationController::OMNIAUTH_OPEN_ID_COMMENT_STRATEGY
  }, :via => [:get]
  post 'auth/open_id_admin/callback', :to => 'admin/sessions#create'
  match 'auth/:provider/callback', :to => 'admin/sessions#create', :via => [:get, :post]
  get 'auth/failure/comments/new', :to => 'comments#new'
  get 'auth/failure', :to => 'admin/sessions#new'

  root :to => 'posts#index'
end

app/models/pubimage.rb
class Pubimage < ActiveRecord::Base
  
  mount_uploader :pimage, PubimageUploader
  # 原始文件名保存在name中，设置在PubfileUploader中设置
  validates  :name, :pimage, :presence => true
  validates :name, uniqueness: true

end

app/controllers/admin/pubimages_controller.rb
class Admin::PubimagesController < Admin::BaseController
  before_filter :find_pubimage, :only => [:show, :update, :destroy, :download]

  def index
    @pubimage = Pubimage.new
    @pubimages = Pubimage.paginate(:page => params[:page]).order("created_at DESC")
  end

  def create
    @pubimage = Pubimage.new(pubimage_params)
    @pubimages = Pubimage.paginate(:page => params[:page]).order("created_at DESC")
    if @pubimage.save!
      respond_to do |format|
        format.html {
          flash[:notice] = "Uploaded File '#{@pubimage.name}'"
          redirect_to(:action => 'index', :id => @page)
        }
      end
    else
      respond_to do |format|
        format.html { render :action => 'index', :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @pubimage.destroy
    @pubimages = Pubimage.paginate(:page => params[:page]).order("created_at DESC")
    respond_to do |format|
      format.html do
        flash[:notice] = "This File has Deleted."
        redirect_to :action => 'index'
      end
      format.json {
        render :json => {
          :message    => "OK",
          :pubimage      => @pubimage.attributes
        }.to_json
      }
    end
  end

  def download
    send_file(@pubimage.pimage.current_path,
        :filename => @pubimage.name,
        :type => "mime/type")
  end

  private

  def pubimage_params
    params.require(:pubimage).permit(:pimage)
  end

  protected

  def find_pubimage
    @pubimage = Pubimage.find(params[:id])
  end
end

app/views/admin/pubimages/_form.html.erb
<%= form.inputs do -%>
  <%= form.input :pimage, :as => :file %>
<% end -%>

app/views/admin/pubimages/_pubimage.html.erb
<tr id="pubimage-<%= pubimage.id %>" class="<%= cycle('', 'alt') %>">
  <td class='created_at'><%= format_create_date(pubimage.created_at) %></td>
  <td><%= link_to(pubimage.name, download_admin_pubimage_path(pubimage))%></td>
  <td><%= link_to(pubimage.pimage.url, pubimage.pimage.url)%></td>
  <td>
    <%= form_for(pubimage, :as => :pubimage, :url => admin_pubimage_path(pubimage), :html => {:class => 'delete-item', :method => :delete}) do |form| -%>
      <%= image_submit_tag("silk/delete.png", :alt => "Delete File") %>
    <% end -%>
  </td>
</tr>

app/views/admin/pubimages/index.html.erb
<h1>图像库</h1>

<%= semantic_form_for([:admin, @pubimage]) do |form| %>
  <%= render :partial => 'form', :locals => {:form => form} %>
  <%= form.actions do %>
    <%= form.action :submit, :as => :button %>
  <% end %>
<% end %>

<table id='pubimages'>
  <thead>
    <tr>
      <th>上传时间</th>
      <th>文件名 (点击链接下载)</th>
      <th>URL地址</th>
      <th>操作</th>
    </tr>
  </thead>

  <tbody>
    <% if @pubimages.empty? -%>
      <tr><td colspan="4">当前没有任何图像.</td></tr>
    <% else -%>
      <%= render :partial => 'pubimage', :collection => @pubimages %>
    <% end -%>
  </tbody>

  <tfoot>
    <% if @pubimages.total_pages > 1 -%>
      <tr class="pagination">
        <td colspan='5'>
          <%= will_paginate(@pubimages, :previous_label => '&lt;&lt; Newer', :next_label => 'Older &gt;&gt;') %>
        </td>
      </tr>
    <% end -%>
  </tfoot>
</table>